name: Karaoke CI + CD

# kara-tools has been changed significantly
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get update

      - name: Install fuse
        run: sudo apt-get install -y fuse3

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF_FILE }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Mount medias
        run: |
          mkdir ./medias
          rclone mount kara0-wpi-moe:downloads/medias ./medias --daemon

#      - name: Download medias
#        run: rclone sync kara0-wpi-moe:downloads/medias ./medias

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup cache for ffmpeg-static
        run: mkdir ~/.cache/

      - run: npx github:weeb-poly/kara-tools

      - name: Unmount medias
        run: fusermount -u ./medias

  deploy:
    needs: [ test ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF_FILE }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Deploy repo
        run: |
          rclone sync karaokes kara0-wpi-moe:downloads/karaokes
          rclone sync lyrics kara0-wpi-moe:downloads/lyrics
          rclone sync tags kara0-wpi-moe:downloads/tags
